name = "svelte-blog"
type = "webpack"

account_id = "ff404933c2aa00ddef4fe1e588481df5"
workers_dev = true
route = "svelte-blog.mattdeboard.workers.dev/*"
zone_id = ""
compatibility_date = "2021-11-18"

[site]
bucket = "./static"
